# Generated by Django 5.1.2 on 2024-10-15 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios_trabajo', '0002_tablero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('max_wip', models.IntegerField(default=0)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='espacios_trabajo.tablero')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
